[package]
name = "vo-runtime-vm"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Runtime support for Vo VM interpreter"

[dependencies]
vo-vm = { path = "../vo-vm" }
vo-runtime-core = { path = "../vo-runtime-core" }
vo-common-core = { path = "../vo-common-core" }
