[package]
name = "vo-web-runtime-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true

description = "WASM platform implementations for Vo stdlib externs"

[lib]
crate-type = ["rlib"]

[dependencies]
vo-runtime = { path = "../../vo-runtime", default-features = false }
js-sys = "0.3"
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3"
features = ["Performance", "Window"]
