[package]
name = "vo-stdlib-native"
version.workspace = true
edition.workspace = true
license.workspace = true

description = "Native platform implementations for Vo stdlib externs"

[dependencies]
vo-runtime = { path = "../vo-runtime", default-features = false, features = ["std"] }
