[package]
name = "vo-runtime-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Vo language runtime core - shared data structures for VM and JIT"

[features]
default = ["std"]
std = ["indexmap"]

[dependencies]
vo-common-core = { path = "../vo-common-core" }
indexmap = { version = "2", optional = true }
