[package]
name = "vo-launcher"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Vo launcher - compile and run Vo programs"

[lib]
name = "vo_launcher"
path = "src/lib.rs"

[[bin]]
name = "vo"
path = "src/main.rs"

[features]
default = ["jit"]
jit = ["vo-vm/jit"]

[dependencies]
vo-common = { path = "../vo-common", features = ["zip"] }
vo-common-core = { path = "../vo-common-core" }
vo-analysis = { path = "../vo-analysis" }
vo-codegen = { path = "../vo-codegen" }
vo-module = { path = "../vo-module" }
vo-runtime = { path = "../vo-runtime" }
vo-vm = { path = "../vo-vm" }
rust-embed = "8"
dirs = "5"
