[package]
name = "vo-test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "vo-test"
path = "src/main.rs"

[dependencies]
vo-engine = { path = "../../../lang/crates/vo-engine" }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
