[package]
name = "vo"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Vo CLI - Command line interface for the Vo programming language"

[[bin]]
name = "vo"
path = "src/main.rs"

[features]
default = ["jit"]
jit = ["vo-engine/jit"]

[dependencies]
vo-engine = { path = "../../../lang/crates/vo-engine" }
vo-vox = { path = "../../../libs/vox/rust" }
